#!/bin/sh

while true
do
  metalsmith
  # start webserver
  cd build
  kill -9 `cat /tmp/pyhttpd.pid`
  python3 -m http.server 8080 &
  echo $! > /tmp/pyhttpd.pid
  cd ..

  inotifywait -e CLOSE_WRITE -r src/ templates/ plugins/
done
